w1[0]="w1l1"
w2[0]="w2l1"
w3[0]="w3l1"
w4[0]="w4l1"
w5[0]="w5l1"
w6[0]="w6l1"
w7[0]="w7l1"
w11[0]="w11l1"
w19[0]="w19l1"
w25[0]="w25l1"
w8[0]="w8l2"
w12[0]="w12l2"
w13[0]="w13l2"
w14[0]="w14l2"
w15[0]="w15l2"
w16[0]="w16l2"
w20[0]="w20l2"
w26[0]="w26l2"
c1[0]="c1l3"
c2[0]="c2l3"
c3[0]="c3l3"
c4[0]="c4l3"
w9[0]="w9l4"
w17[0]="w17l4"
w21[0]="w21l4"
w22[0]="w22l4"
w23[0]="w23l4"
w27[0]="w27l4"
w10[0]="w10l5"
w18[0]="w18l5"
w24[0]="w24l5"
w28[0]="w28l5"
l1[0]="w1l1"
l1[1]="w2l1"
l1[2]="w3l1"
l1[3]="w4l1"
l1[4]="w5l1"
l1[5]="w6l1"
l1[6]="w7l1"
l1[7]="w11l1"
l1[8]="w19l1"
l1[9]="w25l1"
l1[10]="l1s1"
l1[11]="l1s2"
l2[0]="w8l2"
l2[1]="w12l2"
l2[2]="w13l2"
l2[3]="w14l2"
l2[4]="w15l2"
l2[5]="w16l2"
l2[6]="w20l2"
l2[7]="w26l2"
l2[8]="l2s1"
l2[9]="l2s2"
l3[0]="c1l3"
l3[1]="c2l3"
l3[2]="c3l3"
l3[3]="c4l3"
l3[4]="l3s1"
l3[5]="l3s2"
l4[0]="w9l4"
l4[1]="w17l4"
l4[2]="w21l4"
l4[3]="w22l4"
l4[4]="w23l4"
l4[5]="w27l4"
l4[6]="l4s1"
l4[7]="l4s2"
l5[0]="w10l5"
l5[1]="w18l5"
l5[2]="w24l5"
l5[3]="w28l5"
l5[4]="l5s1"
l5[5]="l5s2"
s1[0]="l1s1"
s1[1]="l2s1"
s1[2]="l3s1"
s1[3]="l4s1"
s1[4]="l5s1"
s2[0]="l1s2"
s2[1]="l2s2"
s2[2]="l3s2"
s2[3]="l4s2"
s2[4]="l5s2"
l1[image]="kathara/sdn"
l2[image]="kathara/sdn"
l3[image]="kathara/sdn"
l4[image]="kathara/sdn"
l5[image]="kathara/sdn"
s1[image]="kathara/sdn"
s2[image]="kathara/sdn"
controller[image]="kathara/pox"
controller[0]="M"
l1[12]="M"
l2[10]="M"
l3[6]="M"
l4[8]="M"
l5[6]="M"
s1[5]="M"
s2[5]="M"
w1[num_terms]=0
w2[num_terms]=0
w3[num_terms]=0
w4[num_terms]=0
w5[num_terms]=0
w6[num_terms]=0
w7[num_terms]=0
w8[num_terms]=0
w9[num_terms]=0
w10[num_terms]=0
w11[num_terms]=0
w12[num_terms]=0
w13[num_terms]=0
w14[num_terms]=0
w15[num_terms]=0
w16[num_terms]=0
w17[num_terms]=0
w18[num_terms]=0
w19[num_terms]=0
w20[num_terms]=0
w21[num_terms]=0
w22[num_terms]=0
w23[num_terms]=0
w24[num_terms]=0
w25[num_terms]=0
w26[num_terms]=0
w27[num_terms]=0
w28[num_terms]=0
c1[num_terms]=0
c2[num_terms]=0
c3[num_terms]=0
c4[num_terms]=0
l1[num_terms]=0
l2[num_terms]=0
l3[num_terms]=0
l4[num_terms]=0
l5[num_terms]=0
s1[num_terms]=0
s2[num_terms]=0