from pox.core import core
import pox.openflow.libopenflow_01 as of

log = core.getLogger()

class IncastOptimizer(object):
    def __init__(self):
        # Listening to the flow installation event
        core.IncastController.addListenerByName("OptimizationRequired", self._handle_OptimizationRequired)
        
        # Link capacity in Mbps (used to calculate Queue Drain Time)
        self.C_LINK = 100.0 
        log.info("[OPTIMIZER] Min-Max Queue Drain Time Optimizer started.")

    def _handle_OptimizationRequired(self, event):
        # Data extraction
        procedures = event.procedures
        adjacency = event.adjacency
        ip_to_mac = event.ip_to_mac
        mac_to_location = event.mac_to_location
        collector_dpid_map = event.collector_dpid_map
        spines = event.spines

        if not spines or len(spines) < 2:
            log.warning("[OPTIMIZER] Invalid topology. Missing spines")
            return

        # Filtering procedures that are active
        active_list = []
        for ip, proc in procedures.items():
            # Skip procedures that haven't completed round 1 or have missing data
            if proc['round_number'] < 2 or proc.get('Dv', 0) == 0 or proc.get('Tv', 0) == 0: 
                continue
            
            # Weight = Total Volume to be transmitted by this procedure
            total_volume = len(proc['workers']) * proc['Dv']
            active_list.append({'ip': ip, 'proc': proc, 'weight': total_volume})
            
        if not active_list: 
            return

        # Sorting: Longest Processing Time first (Largest procedures are routed first)
        active_list.sort(key=lambda x: x['weight'], reverse=True)

        # MIN-MAX BOTTLENECK ROUTING ALGORITHM
        flow_mapping = {} # Mapping: (worker_ip, collector_ip) -> chosen_spine_dpid
        
        # Virtual State Matrix tracking the accumulated Volume (Mb) on each unidirectional link.
        # Key: (src_dpid, dst_dpid) -> Value: Accumulated Dv in Megabits
        virtual_link_loads = {}

        log.info("\n[OPTIMIZER] --- COMPUTING NEW RULES (QUEUE DRAIN TIME) ---")

        for entry in active_list:
            collector_ip = entry['ip']
            proc = entry['proc']
            workers = sorted(list(proc['workers']))
            worker_dv = proc['Dv'] # Payload volume generated by a single worker
            
            # Find Collector's Leaf DPID
            c_leaf_dpid = collector_dpid_map.get(collector_ip)
            if not c_leaf_dpid: continue
            
            for w_ip in workers:
                w_mac = ip_to_mac.get(w_ip)
                if not w_mac: continue
                
                # Find Worker's Leaf DPID
                w_leaf_dpid, _ = mac_to_location.get(w_mac, (None, None))
                if not w_leaf_dpid: continue

                # Skip optimization if Worker and Collector are on the same Leaf switch
                if w_leaf_dpid == c_leaf_dpid:
                    continue

                best_spine = None
                min_drain_time = float('inf')

                # Evaluate all possible Spine paths
                for spine in spines:
                    # Retrieve the currently accumulated volume on the two segments of the path
                    vol_up = virtual_link_loads.get((w_leaf_dpid, spine), 0.0)
                    vol_down = virtual_link_loads.get((spine, c_leaf_dpid), 0.0)
                    
                    # Calculate hypothetical Queue Drain Time if we assign this worker here:
                    # Time = (Current Volume + New Worker Volume) / Link Capacity
                    time_up = (vol_up + worker_dv) / self.C_LINK
                    time_down = (vol_down + worker_dv) / self.C_LINK
                    
                    # MAX PHASE: Identify the bottleneck of this specific path
                    # The path is only as fast as its slowest segment (the one taking longer to drain)
                    path_bottleneck_time = max(time_up, time_down)
                    
                    # MIN PHASE: Choose the Spine that offers the lowest bottleneck time
                    if path_bottleneck_time < min_drain_time:
                        min_drain_time = path_bottleneck_time
                        best_spine = spine
                        
                # Route Assignment and State Update
                if best_spine:
                    flow_mapping[(w_ip, collector_ip)] = best_spine
                    
                    # Update the Virtual State Matrix by adding the worker's volume
                    # to both the upstream and downstream links
                    virtual_link_loads[(w_leaf_dpid, best_spine)] = virtual_link_loads.get((w_leaf_dpid, best_spine), 0.0) + worker_dv
                    virtual_link_loads[(best_spine, c_leaf_dpid)] = virtual_link_loads.get((best_spine, c_leaf_dpid), 0.0) + worker_dv

        # Rule deployment
        self._deploy_flow_rules(flow_mapping, adjacency, ip_to_mac, mac_to_location, collector_dpid_map)
        
        log.info("[OPTIMIZER] Routing completed. Processed %d procedures.", len(active_list))

    def _deploy_flow_rules(self, flow_mapping, adjacency, ip_to_mac, mac_to_location, collector_dpid_map):
        for (w_ip, c_ip), spine_dpid in flow_mapping.items():
            w_mac = ip_to_mac.get(w_ip)
            c_mac = ip_to_mac.get(c_ip) # Recuperiamo anche il MAC del collector
            if not w_mac or not c_mac: continue
            
            # Identifying the location of worker and collector (Leaf DPIDs)
            leaf_dpid, _ = mac_to_location.get(w_mac, (None, None))
            collector_dpid = collector_dpid_map.get(c_ip)
            _, collector_port = mac_to_location.get(c_mac, (None, None))
            
            if not leaf_dpid or not collector_dpid: continue

            # If the traffic is local (same leaf switch), no spine routing is needed
            if leaf_dpid == collector_dpid:
                continue

            path_selected = [leaf_dpid, spine_dpid, collector_dpid]
            
            # PASSIAMO I MAC ADDRESS, NON GLI IP
            # Route from ingress leaf switch to the chosen spine switch
            out_port_leaf = adjacency.get(leaf_dpid, {}).get(spine_dpid)
            if out_port_leaf:
                self._install_rule(leaf_dpid, w_mac, c_mac, out_port_leaf)
                
            # Route from the chosen spine switch to the egress leaf switch
            out_port_spine = adjacency.get(spine_dpid, {}).get(collector_dpid)
            if out_port_spine:
                self._install_rule(spine_dpid, w_mac, c_mac, out_port_spine)

            # Final hop
            if collector_port:
                self._install_rule(collector_dpid, w_mac, c_mac, collector_port)
                
            log.info("[OPTIMIZER] Installed L2 path for (%s, %s): %s", w_ip, c_ip, path_selected)

    def _install_rule(self, dpid, src_mac, dst_mac, port):
        msg = of.ofp_flow_mod()
        msg.command = of.OFPFC_MODIFY
        msg.priority = 10
        msg.idle_timeout = 120
        msg.match.dl_src = src_mac
        msg.match.dl_dst = dst_mac
        msg.actions.append(of.ofp_action_output(port=port))
        
        conn = core.openflow.getConnection(dpid)
        if conn: conn.send(msg)
        
def launch():
    core.registerNew(IncastOptimizer)