from pox.core import core
import pox.openflow.libopenflow_01 as of

log = core.getLogger()

class IncastOptimizer(object):
    def __init__(self):
        # Listening to the flow optimization event triggered by the Discovery module
        core.IncastController.addListenerByName("OptimizationRequired", self._handle_OptimizationRequired)
        self.C_LINK = 100.0 
        log.info("[OPTIMIZER] Standard Flow-Splitting Optimizer started.")

    def _handle_OptimizationRequired(self, event):
        # Data extraction
        procedures = event.procedures
        adjacency = event.adjacency
        ip_to_mac = event.ip_to_mac
        mac_to_location = event.mac_to_location
        collector_dpid_map = event.collector_dpid_map
        spines = event.spines
        
        if not spines or len(spines) < 2:
            log.warning("[OPTIMIZER] Invalid topology. Missing spines.")
            return

        # Filtering procedures that are active
        active_list = []
        for ip, proc in procedures.items():
            # Skip procedures that haven't completed round 1 or have missing data
            if proc['round_number'] < 2 or proc.get('Dv', 0) == 0 or proc.get('Tv', 0) == 0: 
                continue
            
            # Weight = Total volume generated by all workers of this procedure
            total_volume = len(proc['workers']) * proc['Dv']
            active_list.append({'ip': ip, 'proc': proc, 'weight': total_volume})
            
        if not active_list: 
            return

        # Sorting procedures by weight (Longest Processing Time first)
        active_list.sort(key=lambda x: x['weight'], reverse=True)
        flow_mapping = {} # Mapping: (worker_ip, collector_ip) -> spine_dpid
        spine_loads = {s: 0.0 for s in spines}

        log.info("\n[OPTIMIZER] --- COMPUTING NEW RULES (STANDARD LOAD BALANCING) ---")

        for entry in active_list:
            collector_ip = entry['ip']
            proc = entry['proc']
            workers = sorted(list(proc['workers']))
            
            for w_ip in workers:
                # Choosing the spine with the smallest accumulated volume
                chosen_spine = min(spine_loads, key=spine_loads.get)
                flow_mapping[(w_ip, collector_ip)] = chosen_spine
                
                # Updating the global load on the chosen spine
                spine_loads[chosen_spine] += proc['Dv']
                
        log.info("[OPTIMIZER] Estimated global spine loading: %s", 
                 {f"S{k}": f"{v:.1f}Mb" for k, v in spine_loads.items()})

        # Rule deployment
        self._deploy_flow_rules(flow_mapping, adjacency, ip_to_mac, mac_to_location, collector_dpid_map)

    def _deploy_flow_rules(self, flow_mapping, adjacency, ip_to_mac, mac_to_location, collector_dpid_map):
        for (w_ip, c_ip), spine_dpid in flow_mapping.items():
            w_mac = ip_to_mac.get(w_ip)
            c_mac = ip_to_mac.get(c_ip) # Recuperiamo anche il MAC del collector
            if not w_mac or not c_mac: continue
            
            # Identifying the location of worker and collector (Leaf DPIDs)
            leaf_dpid, _ = mac_to_location.get(w_mac, (None, None))
            collector_dpid = collector_dpid_map.get(c_ip)
            _, collector_port = mac_to_location.get(c_mac, (None, None))
            
            if not leaf_dpid or not collector_dpid: continue

            # If the traffic is local (same leaf switch), no spine routing is needed
            if leaf_dpid == collector_dpid:
                continue

            path_selected = [leaf_dpid, spine_dpid, collector_dpid]
            
            # PASSIAMO I MAC ADDRESS, NON GLI IP
            # Route from ingress leaf switch to the chosen spine switch
            out_port_leaf = adjacency.get(leaf_dpid, {}).get(spine_dpid)
            if out_port_leaf:
                self._install_rule(leaf_dpid, w_mac, c_mac, out_port_leaf)
                
            # Route from the chosen spine switch to the egress leaf switch
            out_port_spine = adjacency.get(spine_dpid, {}).get(collector_dpid)
            if out_port_spine:
                self._install_rule(spine_dpid, w_mac, c_mac, out_port_spine)

            # Final hop
            if collector_port:
                self._install_rule(collector_dpid, w_mac, c_mac, collector_port)
                
            log.info("[OPTIMIZER] Installed L2 path for (%s, %s): %s", w_ip, c_ip, path_selected)

    def _install_rule(self, dpid, src_mac, dst_mac, port):
        msg = of.ofp_flow_mod()
        msg.command = of.OFPFC_MODIFY
        msg.priority = 10
        msg.idle_timeout = 120
        msg.match.dl_src = src_mac
        msg.match.dl_dst = dst_mac
        msg.actions.append(of.ofp_action_output(port=port))
        
        conn = core.openflow.getConnection(dpid)
        if conn: conn.send(msg)

def launch():
    core.registerNew(IncastOptimizer)