# host Images
h1[image]="kathara/base"
h2[image]="kathara/base"
h3[image]="kathara/base"
h4[image]="kathara/base"

# service functions (can be implemented as P4 reflectors or simple base reflectors)
sf1[image]="kathara/p4"
sf2[image]="kathara/p4"
sf3[image]="kathara/p4"

a[image]="kathara/p4"
b[image]="kathara/p4"
c[image]="kathara/p4"
d[image]="kathara/p4"
e[image]="kathara/p4"
f[image]="kathara/p4"
g[image]="kathara/p4"
h[image]="kathara/p4"

# host to classifier (Node a)
h1[0]="h1_a"
a[0]="h1_a"

h2[0]="h2_a"
a[1]="h2_a"

# classifier (a) to Underlay core
a[2]="a_b"
b[0]="a_b"

a[3]="a_c"
c[0]="a_c"

# Underlay Mesh connections
b[1]="b_c"
c[1]="b_c"

b[2]="b_d"
d[0]="b_d"

b[3]="b_f"
f[0]="b_f"

c[2]="c_e"
e[0]="c_e"

c[3]="c_g"
g[0]="c_g"

# sff1 (d) connections to service functions and core
d[1]="d_f"
f[1]="d_f"

d[2]="d_sf1"
sf1[0]="d_sf1"

d[3]="d_sf2"
sf2[0]="d_sf2"

# sff2 (e) connections to service functions and core
e[1]="e_g"
g[1]="e_g"

e[2]="e_sf3"
sf3[0]="e_sf3"

# egress core connections
f[2]="f_g"
g[2]="f_g"

f[3]="f_h"
h[0]="f_h"

g[3]="g_h"
h[1]="g_h"

# egress to destination hosts
h[2]="h_h3"
h3[0]="h_h3"

h[3]="h_h4"
h4[0]="h_h4"
